# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ProcessDataInput(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, customers_file: str=None, transactions_file: str=None, items_file: str=None):  # noqa: E501
        """ProcessDataInput - a model defined in Swagger

        :param customers_file: The customers_file of this ProcessDataInput.  # noqa: E501
        :type customers_file: str
        :param transactions_file: The transactions_file of this ProcessDataInput.  # noqa: E501
        :type transactions_file: str
        :param items_file: The items_file of this ProcessDataInput.  # noqa: E501
        :type items_file: str
        """
        self.swagger_types = {
            'customers_file': str,
            'transactions_file': str,
            'items_file': str
        }

        self.attribute_map = {
            'customers_file': 'customers_file',
            'transactions_file': 'transactions_file',
            'items_file': 'items_file'
        }
        self._customers_file = customers_file
        self._transactions_file = transactions_file
        self._items_file = items_file

    @classmethod
    def from_dict(cls, dikt) -> 'ProcessDataInput':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ProcessDataInput of this ProcessDataInput.  # noqa: E501
        :rtype: ProcessDataInput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def customers_file(self) -> str:
        """Gets the customers_file of this ProcessDataInput.


        :return: The customers_file of this ProcessDataInput.
        :rtype: str
        """
        return self._customers_file

    @customers_file.setter
    def customers_file(self, customers_file: str):
        """Sets the customers_file of this ProcessDataInput.


        :param customers_file: The customers_file of this ProcessDataInput.
        :type customers_file: str
        """

        self._customers_file = customers_file

    @property
    def transactions_file(self) -> str:
        """Gets the transactions_file of this ProcessDataInput.


        :return: The transactions_file of this ProcessDataInput.
        :rtype: str
        """
        return self._transactions_file

    @transactions_file.setter
    def transactions_file(self, transactions_file: str):
        """Sets the transactions_file of this ProcessDataInput.


        :param transactions_file: The transactions_file of this ProcessDataInput.
        :type transactions_file: str
        """

        self._transactions_file = transactions_file

    @property
    def items_file(self) -> str:
        """Gets the items_file of this ProcessDataInput.


        :return: The items_file of this ProcessDataInput.
        :rtype: str
        """
        return self._items_file

    @items_file.setter
    def items_file(self, items_file: str):
        """Sets the items_file of this ProcessDataInput.


        :param items_file: The items_file of this ProcessDataInput.
        :type items_file: str
        """

        self._items_file = items_file
