# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ProcessDataOutput(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, output_file: str=None):  # noqa: E501
        """ProcessDataOutput - a model defined in Swagger

        :param output_file: The output_file of this ProcessDataOutput.  # noqa: E501
        :type output_file: str
        """
        self.swagger_types = {
            'output_file': str
        }

        self.attribute_map = {
            'output_file': 'output_file'
        }
        self._output_file = output_file

    @classmethod
    def from_dict(cls, dikt) -> 'ProcessDataOutput':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ProcessDataOutput of this ProcessDataOutput.  # noqa: E501
        :rtype: ProcessDataOutput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def output_file(self) -> str:
        """Gets the output_file of this ProcessDataOutput.


        :return: The output_file of this ProcessDataOutput.
        :rtype: str
        """
        return self._output_file

    @output_file.setter
    def output_file(self, output_file: str):
        """Sets the output_file of this ProcessDataOutput.


        :param output_file: The output_file of this ProcessDataOutput.
        :type output_file: str
        """

        self._output_file = output_file
