version: 1
filters:
  request_id:
    (): flask_log_request_id.RequestIDLogFilter
  runid:
    (): LogFilter.ContextFilter
formatters:
  simple:
    format: '["%(levelname)s", "epoch":"%(created)f", "ts":"%(asctime)s", "pid":"%(process)d", "runid":"%(request_id)s", "corrid":"corrid", "pathname":"%(pathname)s","line":"%(lineno)d", "msg":"%(message)s"]'
    datefmt: '%a %b %d %H:%M:%S %Y'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    filters: [request_id]
loggers:
  simpleExample:
    level: INFO
    handlers: [console]
root:
  level: DEBUG
  handlers: [console]